"Vim Options: http://vimdoc.sourceforge.net/htmldoc/options.html

"編碼 - Encode
set encoding=utf-8                    "(enc)
set fileencodings=ucs-bom,utf-8,cp950 "(fencs)
"set termencoding=utf-8              "(tenc)

"基本配置
syntax on
syntax enable
set nocompatible    "(nocp) 不與 vi 相容
set showmode        "(smd)
set showcmd         "(sc)
set fileformat=unix "(ff)
colo torte
filetype plugin indent on

"啟用鼠標 - Mouse
set mouse=a
set selection=exclusive  "(sel)
set selectmode=mouse,key "(slm)

"縮行 - Indent
set autoindent      "(ai) 繼承前一行縮行
set smartindent     "(si) 偵測括號 {}
set cindent         "(cin) 偵測 C 程式語言
set expandtab       "(et) 輸入 Tab 轉換成 Space
set tabstop=8       "(ts) Tab 顯示為 8 個空格
set shiftwidth=4    "(sw) 縮行寬度
set softtabstop=0 smarttab     "(sts) Backspace 寬度
set backspace=eol,start,indent "(bs)

"外觀
set ruler           "(ru) 顯示標尺
set number          "(nu) 顯示行號
"set relativenumber "(rnu) 顯示相對行號
set cursorline      "(cul) 顯示當前行
"set cursorcolumn   "(cuc) 顯示當前列
"set textwidth=80   "(tw)
set wrap            "自動換行
set linebreak       "(lbr) 不在單字中斷行
set wrapmargin=2    "(wm)
set laststatus=3    "(ls) 顯示狀態欄 0=不顯示 1=多視窗才顯示 2=顯示
set scrolloff=3     "(so) 保持上方下方三行距離

"用淺色高亮顯示當前行
autocmd InsertLeave * set nocursorline
autocmd InsertEnter * set cursorline

"搜尋 - Search
set hlsearch   "(hls) 高亮顯示匹配結果
set incsearch  "(is) 每輸入一個字符 就自動跳到第一個匹配的結果
set ignorecase "(ic) 搜尋字串不分大小寫
set smartcase  "(scs) 部分大寫字母的搜索詞時 搜尋字串區分大小寫
set showmatch  "(sm) 顯示括號匹配 ()[]{}

"編輯 - Edit
"set spell spelllang=en_us "檢查英文拼寫
set nobackup        "(nobk) 不產生備份檔案 filename~
set noswapfile      "(noswf) 不產生交換檔案 .filename.swap
"set undofile       "(udf) 保留 undo 歷史紀錄
set backupdir=~/.vim/.backup//  "(bdir)
set directory=~/.vim/.swp//     "(dir)
set undodir=~/.vim/.undo//      "(udir)
"set autochdir       "(acd) 自動切換目錄
set history=1000    "(hi) 紀錄歷史紀錄次數
set autoread        "(ar) 偵測檔案被外部修改
set listchars=tab:▸\ ,trail:·,extends:>,precedes:< " (lcs) 行尾有多餘的空格和 Tab 顯示其符號
set list
set wildmenu        "(wmnu) 自動補全(tab) menu 指令
set wildmode=longest:list,full  "(wim)
set noerrorbells    "(noeb) 關閉錯誤訊息鈴聲
set visualbell      "(vb) 顯示可視化提示
set pastetoggle=<F12> "(pt) F12 switch paste mode

if has('clipboard')
  set clipboard+=unnamedplus    "與系統剪貼簿整合 / Use system clipboard
endif

"Automatically remove trailing spaces when saving a file.
augroup TrimWhitespace
  autocmd!
  autocmd BufWritePre * silent! keeppatterns %s/\s\+$//e
augroup END

"Avoiding redrawtime exceeded syntax highlighting disabled issue
set re=0
