# Move into ~/.config/topgrade.d/
[misc]
pre_sudo = true
assume_yes = true
no_retry = true
disable = ["containers", "pip3"]
no_self_update = true

[brew]
greedy_cask = true
greedy_latest = true
autoremove = true

[git]
max_concurrency = 4
repos = [
  "~/.dotfiles"
]
pull_predefined = false